app:
  product-api:
    base-url: http://product-api:8080
  customer-api:
    base-url: http://customer-api:8080
  retry:
    max-attempts: 5
    initial-delay: 1
  webclient:
    timeout: 10
    max-memory-size: 1MB

spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:orders}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  server:
    port: 8080
